# Generated by Django 4.2 on 2023-04-15 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("epicevents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_client",
            field=models.BooleanField(default=False, verbose_name="Is client ?"),
        ),
        migrations.AlterField(
            model_name="client",
            name="sales_contact",
            field=models.ForeignKey(
                limit_choices_to={"team_id": 2},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_sales_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date updated"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Is signed"),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                ("payment_due", models.DateTimeField(verbose_name="Payment due")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="epicevents.client",
                    ),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        limit_choices_to={"team_id": 2},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
