# Generated by Django 4.2 on 2023-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epicevents",
            "0002_alter_client_is_client_alter_client_sales_contact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateField(verbose_name="Payment due"),
        ),
    ]
