# Generated by Django 4.2 on 2023-04-15 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epicevents", "0004_alter_contract_sales_contact_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="contract",
            new_name="client_contract",
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Attendees",
            ),
        ),
    ]
